# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(max_length=11)),
                ('pickup_city', models.CharField(max_length=20)),
                ('dropoff_city', models.CharField(max_length=20)),
                ('fruit', models.CharField(max_length=10)),
                ('fruit_quantity', models.IntegerField()),
                ('service_date', models.DateField()),
                ('service_time', models.TimeField()),
                ('requested_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_number', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_longitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('current_latitude', models.DecimalField(decimal_places=4, max_digits=7)),
                ('current_address', models.TextField()),
                ('created_on', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.TrackDevice')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('income', models.DecimalField(decimal_places=2, max_digits=7)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Request')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=8)),
                ('vehicle_model', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TruckDriver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('license_number', models.CharField(max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Company')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Person')),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.TruckDriver'),
        ),
        migrations.AddField(
            model_name='trackdevice',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.TruckDriver'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Person'),
        ),
    ]
