# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrosealapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'verbose_name_plural': 'Requests'},
        ),
        migrations.AlterModelOptions(
            name='trackdevice',
            options={'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterModelOptions(
            name='trackevent',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'verbose_name_plural': 'Trucks'},
        ),
        migrations.AlterModelOptions(
            name='truckdriver',
            options={'verbose_name_plural': 'Drivers'},
        ),
        migrations.RenameField(
            model_name='trackdevice',
            old_name='imei_number',
            new_name='ref_number',
        ),
        migrations.AddField(
            model_name='request',
            name='customer_name',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='request_phone',
            field=models.CharField(default='08056163533', max_length=11),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='company',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Company'),
        ),
        migrations.AlterField(
            model_name='truckdriver',
            name='referee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agrosealapp.Person'),
        ),
    ]
