# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-23 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosealapp', '0003_auto_20170809_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truckrequest',
            old_name='customer_phone',
            new_name='mobile_money',
        ),
        migrations.AddField(
            model_name='truckrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
            preserve_default=False,
        ),
    ]
