# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrosealapp', '0004_auto_20170823_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckrequest',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='dropoff_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='fruit',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='fruit_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='mobile_money',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='pickup_city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='request_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='service_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='truckrequest',
            name='service_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
